id: P009614
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9252
  title: འབྲུག་པ་བཀའ་བརྒྱུད་པའི་ལོ་རྒྱུས་ཀྱི་དཔྱད་གཞི་ཡིག་རིགས།
  author: ''
  volumes:
    74ce348619c841be93bc14273b7088f5:
      image_group_id: I1KG9494
      title: ''
      volume_number: 1
      total_pages: 96
