id: I18599EF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:50:25+00:00'
last_modified: '2022-06-08T12:16:36.948719+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9252
  title: འབྲུག་པ་བཀའ་བརྒྱུད་པའི་ལོ་རྒྱུས་ཀྱི་དཔྱད་གཞི་ཡིག་རིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    '1499':
      image_group_id: I1KG9494
      title: ''
      total_pages: 96
      order: 1
      base_file: 1499.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
